### PR TITLE
Increase the version upperbound of the dependencies so the extensions can be used in .NetCore 3.x apps

### PR DESCRIPTION
**Pull request by groovyfeng**

### CODE REVIEW

**Comment by xuzhg** [comment]
Merged manually at: 2d1cb003a4a23a1de754c71037b1b5397148ac34

**Comment by weitzhandler** [comment]
Can we please get this update released and pushed to NuGet so we can start using it in our .NET Core 3 projects?

**Comment by groovyfeng** [comment]
We are validating it and will publish soon (hopefully this week).

**Comment by weitzhandler** [comment]
Thanks for your update!

**Pull request closed without merging**
