### PR TITLE
Add OData Migration Extension

### PR DESCRIPTION
**Pull request by aayc**
The OData Migration extension allows OData V4 services to support V3 clients, provided that the V4 service has access to its V3 EDMX contract.

The OData Migration extension has three main components - URL translation (including path and query), request body translation, and response body translation.  URL translation components are found in the Middleware folder of the Microsoft.Extensions.OData.Migration project, whereas request and response body translation can be found in Formatters/Deserialization and Formatters/Serialization respectively.

In addition, there is a suite of unit and E2E tests with the project.  More E2E tests are in the process of being written at the time of this pull request.

### CODE REVIEW

**Comment by xuzhg** [comment]
@aayc Is it still active? Would you please rebase it and resolve the conflicts?

**Comment by aayc** [comment]
> @aayc Is it still active? Would you please rebase it and resolve the conflicts?

**Comment by aayc** [comment]
@xuzhg Yes, this is pending review from the OData team.  Looks like Github reports no conflicts with base branch yet - did you want me to rebase to different branch than master?

**Comment by xuzhg** [comment]
Merged at other PR. #15. If not, please reopen it.

**Pull request closed without merging**
